### ISSUE TITLE
[Issue]: Linking against GTL library with GPU-awared MPICH

### ISSUE THREAD

**Issue by vitduck** [ROCm/rocHPL-MxP#1]
### Problem Description

The following error was observed on AAC when built MxP agains Cray MPICH
```
$ srun -n 2 ./build/run_rochplmxp -P 1 -Q 2 -N 229376 --NB 2048

MPICH ERROR [Rank 0] [job id 1779.1] [Sun Oct 20 02:25:38 2024] [x9000c1s5b0n0] - Abort(-1) (rank 0 in comm 0): MPIDI_CRAY_init: GPU_SUPPORT_ENABLED is requested, but GTL library is not linked
 (Other MPI error)

aborting job:
MPIDI_CRAY_init: GPU_SUPPORT_ENABLED is requested, but GTL library is not linked
```

### Operating System

Red Hat Enterprise Linux 8

### CPU

MI300A

### GPU

MI300A

### ROCm Version

ROCm 6.2.1

### Steps to Reproduce

1. Modules: 
```
  1) craype-x86-rome   2) libfabric/1.20.1   3) craype-network-ofi   4) perftools-base/23.12.0   5) cce/17.0.1   6) craype/2.7.31.11   7) cray-dsmml/0.3.0   8) cray-mpich/8.1.29   9) cray-libsci/24.03.0  10) PrgEnv-cray/8.5.0
```

2. Built: 
```
./install.sh \
   --prefix=...  \
   --with-mpi=/opt/cray/pe/mpich/8.1.29/ofi/cray/16.0
```

Please update the install script to link against GTL.

**Comment by ppanchad-amd** [comment]
Hi @vitduck. Internal ticket has been created to investigate your issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @vitduck, GTL is an HPE library that you need to link yourself according to Cray MIPCH documentation: https://docs.nersc.gov/development/programming-models/mpi/cray-mpich/. Please also make sure that you have the appropriate AMD modules loaded as documented in section 2 of https://cpe.ext.hpe.com/docs/latest/mpt/mpich/intro_mpi.html

**Comment by vitduck** [comment]
It is indeed a module-related problem. 

The GTL library is now linked correctly after adding accelerator module 
- `craype-accel-amd-gfx`

@ppanchad-amd @zichguan-amd  
Thanks very much for your help. 
Regards.
